name: .NET Publish

on:
  pull_request:
    branches: [ "master" ]
    types: [ closed ]

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish project
        run: dotnet publish -c Release -o ./publish

      - name: Upload published files
        uses: actions/upload-artifact@v4
        with:
          name: published-output
          path: ./publish
